# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170413_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclick',
            name='username',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
