# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 14:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20170413_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBlacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('video_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='userclick',
            name='recenttime',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 20, 14, 33, 5, 461256, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userblacklist',
            unique_together=set([('video_id', 'username')]),
        ),
    ]
